from __future__ import annotations

from functools import lru_cache
from pathlib import Path
import tkinter as tk
from tkinter import ttk

try:
    from PIL import Image, ImageTk
except Exception:  # pragma: no cover - Pillow is optional at runtime
    Image = None
    ImageTk = None


THEMES = {
    "day": {
        "name": "DIA",
        "bg": "#f7fafc",
        "panel": "#ffffff",
        "panel_alt": "#eef2f7",
        "text": "#111827",
        "muted": "#374151",
        "primary": "#0f766e",
        "primary_text": "#ffffff",
        "danger": "#b91c1c",
        "warning": "#b45309",
        "button": "#1d4ed8",
        "button_text": "#ffffff",
        "input_bg": "#ffffff",
        "input_text": "#111827",
        "tree_bg": "#ffffff",
        "tree_fg": "#111827",
        "tree_heading": "#dbeafe",
    },
    "night": {
        "name": "NOCHE",
        "bg": "#050505",
        "panel": "#111827",
        "panel_alt": "#1f2937",
        "text": "#f9fafb",
        "muted": "#d1d5db",
        "primary": "#22c55e",
        "primary_text": "#052e16",
        "danger": "#ef4444",
        "warning": "#facc15",
        "button": "#16a34a",
        "button_text": "#04130a",
        "input_bg": "#000000",
        "input_text": "#ffffff",
        "tree_bg": "#0f172a",
        "tree_fg": "#f8fafc",
        "tree_heading": "#14532d",
    },
    "emerald": {
        "name": "ESMERALDA",
        "bg": "#edf7f2",
        "panel": "#ffffff",
        "panel_alt": "#dff1e8",
        "text": "#10231c",
        "muted": "#315447",
        "primary": "#047857",
        "primary_text": "#ffffff",
        "danger": "#b91c1c",
        "warning": "#a16207",
        "button": "#0f766e",
        "button_text": "#ffffff",
        "input_bg": "#ffffff",
        "input_text": "#10231c",
        "tree_bg": "#ffffff",
        "tree_fg": "#10231c",
        "tree_heading": "#bbf7d0",
    },
    "graphite": {
        "name": "GRAFITO",
        "bg": "#161a20",
        "panel": "#232933",
        "panel_alt": "#303846",
        "text": "#f8fafc",
        "muted": "#cbd5e1",
        "primary": "#38bdf8",
        "primary_text": "#082f49",
        "danger": "#fb7185",
        "warning": "#fbbf24",
        "button": "#2563eb",
        "button_text": "#ffffff",
        "input_bg": "#0f172a",
        "input_text": "#f8fafc",
        "tree_bg": "#111827",
        "tree_fg": "#f8fafc",
        "tree_heading": "#1e40af",
    },
    "bakery": {
        "name": "PANADERIA",
        "bg": "#fff7ed",
        "panel": "#ffffff",
        "panel_alt": "#ffedd5",
        "text": "#2f1b12",
        "muted": "#6b4f3f",
        "primary": "#c2410c",
        "primary_text": "#ffffff",
        "danger": "#b91c1c",
        "warning": "#ca8a04",
        "button": "#9a3412",
        "button_text": "#ffffff",
        "input_bg": "#fffaf5",
        "input_text": "#2f1b12",
        "tree_bg": "#ffffff",
        "tree_fg": "#2f1b12",
        "tree_heading": "#fed7aa",
    },
    "sunset": {
        "name": "SUNSET",
        "bg": "#fff4f0",
        "panel": "#ffffff",
        "panel_alt": "#ffe4d6",
        "text": "#2a1a15",
        "muted": "#6f4d42",
        "primary": "#ef4444",
        "primary_text": "#ffffff",
        "danger": "#b91c1c",
        "warning": "#f59e0b",
        "button": "#c2410c",
        "button_text": "#ffffff",
        "input_bg": "#fffaf8",
        "input_text": "#2a1a15",
        "tree_bg": "#ffffff",
        "tree_fg": "#2a1a15",
        "tree_heading": "#fecaca",
    },
    "ocean": {
        "name": "OCEANO",
        "bg": "#eff6ff",
        "panel": "#ffffff",
        "panel_alt": "#dbeafe",
        "text": "#0f172a",
        "muted": "#334155",
        "primary": "#0ea5e9",
        "primary_text": "#082f49",
        "danger": "#dc2626",
        "warning": "#ca8a04",
        "button": "#0369a1",
        "button_text": "#ffffff",
        "input_bg": "#ffffff",
        "input_text": "#0f172a",
        "tree_bg": "#ffffff",
        "tree_fg": "#0f172a",
        "tree_heading": "#bae6fd",
    },
    "neon": {
        "name": "NEON",
        "bg": "#0b1020",
        "panel": "#111827",
        "panel_alt": "#1f2937",
        "text": "#e2e8f0",
        "muted": "#a5b4fc",
        "primary": "#22d3ee",
        "primary_text": "#06202a",
        "danger": "#fb7185",
        "warning": "#facc15",
        "button": "#7c3aed",
        "button_text": "#ffffff",
        "input_bg": "#020617",
        "input_text": "#e2e8f0",
        "tree_bg": "#0f172a",
        "tree_fg": "#e2e8f0",
        "tree_heading": "#1d4ed8",
    },
    "contrast": {
        "name": "CONTRASTE",
        "bg": "#000000",
        "panel": "#101010",
        "panel_alt": "#222222",
        "text": "#ffffff",
        "muted": "#fef08a",
        "primary": "#facc15",
        "primary_text": "#000000",
        "danger": "#ff4d4d",
        "warning": "#facc15",
        "button": "#ffffff",
        "button_text": "#000000",
        "input_bg": "#000000",
        "input_text": "#ffffff",
        "tree_bg": "#000000",
        "tree_fg": "#ffffff",
        "tree_heading": "#facc15",
    },
    "midnight": {
        "name": "MIDNIGHT",
        "bg": "#0b1120",
        "panel": "#111827",
        "panel_alt": "#1e293b",
        "text": "#f8fafc",
        "muted": "#cbd5e1",
        "primary": "#38bdf8",
        "primary_text": "#082f49",
        "danger": "#fb7185",
        "warning": "#fbbf24",
        "button": "#1d4ed8",
        "button_text": "#ffffff",
        "input_bg": "#020617",
        "input_text": "#f8fafc",
        "tree_bg": "#0f172a",
        "tree_fg": "#f8fafc",
        "tree_heading": "#1d4ed8",
    },
    "rose": {
        "name": "ROSA",
        "bg": "#fff1f2",
        "panel": "#ffffff",
        "panel_alt": "#ffe4e6",
        "text": "#431827",
        "muted": "#7f1d1d",
        "primary": "#e11d48",
        "primary_text": "#ffffff",
        "danger": "#be123c",
        "warning": "#f59e0b",
        "button": "#9f1239",
        "button_text": "#ffffff",
        "input_bg": "#fff7f7",
        "input_text": "#431827",
        "tree_bg": "#ffffff",
        "tree_fg": "#431827",
        "tree_heading": "#fecdd3",
    },
    "sand": {
        "name": "ARENA",
        "bg": "#fff8ef",
        "panel": "#ffffff",
        "panel_alt": "#f5e6d3",
        "text": "#3f2d1f",
        "muted": "#6b4f3f",
        "primary": "#d97706",
        "primary_text": "#ffffff",
        "danger": "#b91c1c",
        "warning": "#b45309",
        "button": "#92400e",
        "button_text": "#ffffff",
        "input_bg": "#fffdf8",
        "input_text": "#3f2d1f",
        "tree_bg": "#ffffff",
        "tree_fg": "#3f2d1f",
        "tree_heading": "#fde68a",
    },
    "mint": {
        "name": "MENTA",
        "bg": "#ecfdf5",
        "panel": "#ffffff",
        "panel_alt": "#d1fae5",
        "text": "#0f172a",
        "muted": "#065f46",
        "primary": "#10b981",
        "primary_text": "#ffffff",
        "danger": "#dc2626",
        "warning": "#ca8a04",
        "button": "#047857",
        "button_text": "#ffffff",
        "input_bg": "#f8fffc",
        "input_text": "#0f172a",
        "tree_bg": "#ffffff",
        "tree_fg": "#0f172a",
        "tree_heading": "#a7f3d0",
    },
    "lagoon": {
        "name": "LAGUNA",
        "bg": "#eff8ff",
        "panel": "#ffffff",
        "panel_alt": "#dbeafe",
        "text": "#0f172a",
        "muted": "#334155",
        "primary": "#0284c7",
        "primary_text": "#ffffff",
        "danger": "#dc2626",
        "warning": "#ca8a04",
        "button": "#0369a1",
        "button_text": "#ffffff",
        "input_bg": "#ffffff",
        "input_text": "#0f172a",
        "tree_bg": "#ffffff",
        "tree_fg": "#0f172a",
        "tree_heading": "#bae6fd",
    },
    "forest": {
        "name": "BOSQUE",
        "bg": "#f0fdf4",
        "panel": "#ffffff",
        "panel_alt": "#dcfce7",
        "text": "#10231c",
        "muted": "#315447",
        "primary": "#15803d",
        "primary_text": "#ffffff",
        "danger": "#b91c1c",
        "warning": "#a16207",
        "button": "#166534",
        "button_text": "#ffffff",
        "input_bg": "#f9fffb",
        "input_text": "#10231c",
        "tree_bg": "#ffffff",
        "tree_fg": "#10231c",
        "tree_heading": "#bbf7d0",
    },
    "amber": {
        "name": "AMBAR",
        "bg": "#fffbeb",
        "panel": "#ffffff",
        "panel_alt": "#fef3c7",
        "text": "#422006",
        "muted": "#78350f",
        "primary": "#f59e0b",
        "primary_text": "#111111",
        "danger": "#b91c1c",
        "warning": "#d97706",
        "button": "#b45309",
        "button_text": "#ffffff",
        "input_bg": "#fffdf3",
        "input_text": "#422006",
        "tree_bg": "#ffffff",
        "tree_fg": "#422006",
        "tree_heading": "#fde68a",
    },
    "coral": {
        "name": "CORAL",
        "bg": "#fff5f5",
        "panel": "#ffffff",
        "panel_alt": "#ffe4e6",
        "text": "#2a1a15",
        "muted": "#7c2d12",
        "primary": "#f97316",
        "primary_text": "#ffffff",
        "danger": "#dc2626",
        "warning": "#ea580c",
        "button": "#c2410c",
        "button_text": "#ffffff",
        "input_bg": "#fffaf8",
        "input_text": "#2a1a15",
        "tree_bg": "#ffffff",
        "tree_fg": "#2a1a15",
        "tree_heading": "#fed7aa",
    },
    "orchid": {
        "name": "ORQUIDEA",
        "bg": "#faf5ff",
        "panel": "#ffffff",
        "panel_alt": "#f3e8ff",
        "text": "#2e1065",
        "muted": "#6b21a8",
        "primary": "#7c3aed",
        "primary_text": "#ffffff",
        "danger": "#be123c",
        "warning": "#d97706",
        "button": "#6d28d9",
        "button_text": "#ffffff",
        "input_bg": "#fffaff",
        "input_text": "#2e1065",
        "tree_bg": "#ffffff",
        "tree_fg": "#2e1065",
        "tree_heading": "#e9d5ff",
    },
    "steel": {
        "name": "ACERO",
        "bg": "#f8fafc",
        "panel": "#ffffff",
        "panel_alt": "#e2e8f0",
        "text": "#0f172a",
        "muted": "#475569",
        "primary": "#475569",
        "primary_text": "#ffffff",
        "danger": "#b91c1c",
        "warning": "#b45309",
        "button": "#334155",
        "button_text": "#ffffff",
        "input_bg": "#ffffff",
        "input_text": "#0f172a",
        "tree_bg": "#ffffff",
        "tree_fg": "#0f172a",
        "tree_heading": "#cbd5e1",
    },
    "cobalt": {
        "name": "COBALTO",
        "bg": "#eef6ff",
        "panel": "#ffffff",
        "panel_alt": "#dbeafe",
        "text": "#0f172a",
        "muted": "#334155",
        "primary": "#2563eb",
        "primary_text": "#ffffff",
        "danger": "#dc2626",
        "warning": "#d97706",
        "button": "#1d4ed8",
        "button_text": "#ffffff",
        "input_bg": "#ffffff",
        "input_text": "#0f172a",
        "tree_bg": "#ffffff",
        "tree_fg": "#0f172a",
        "tree_heading": "#bfdbfe",
    },
    "aurora": {
        "name": "AURORA",
        "bg": "#f0fdf4",
        "panel": "#ffffff",
        "panel_alt": "#dcfce7",
        "text": "#10231c",
        "muted": "#315447",
        "primary": "#14b8a6",
        "primary_text": "#ffffff",
        "danger": "#ef4444",
        "warning": "#f59e0b",
        "button": "#0f766e",
        "button_text": "#ffffff",
        "input_bg": "#ffffff",
        "input_text": "#10231c",
        "tree_bg": "#ffffff",
        "tree_fg": "#10231c",
        "tree_heading": "#99f6e4",
    },
    "ruby": {
        "name": "RUBI",
        "bg": "#fff1f2",
        "panel": "#ffffff",
        "panel_alt": "#ffe4e6",
        "text": "#3f1d2e",
        "muted": "#7f1d1d",
        "primary": "#be123c",
        "primary_text": "#ffffff",
        "danger": "#991b1b",
        "warning": "#f59e0b",
        "button": "#9f1239",
        "button_text": "#ffffff",
        "input_bg": "#fff7f7",
        "input_text": "#3f1d2e",
        "tree_bg": "#ffffff",
        "tree_fg": "#3f1d2e",
        "tree_heading": "#fecdd3",
    },
    "lavender": {
        "name": "LAVANDA",
        "bg": "#faf5ff",
        "panel": "#ffffff",
        "panel_alt": "#ede9fe",
        "text": "#2e1065",
        "muted": "#6b21a8",
        "primary": "#8b5cf6",
        "primary_text": "#ffffff",
        "danger": "#be123c",
        "warning": "#d97706",
        "button": "#7c3aed",
        "button_text": "#ffffff",
        "input_bg": "#ffffff",
        "input_text": "#2e1065",
        "tree_bg": "#ffffff",
        "tree_fg": "#2e1065",
        "tree_heading": "#ddd6fe",
    },
    "sunrise": {
        "name": "AMANECER",
        "bg": "#fff7ed",
        "panel": "#ffffff",
        "panel_alt": "#ffedd5",
        "text": "#422006",
        "muted": "#7c2d12",
        "primary": "#f97316",
        "primary_text": "#ffffff",
        "danger": "#dc2626",
        "warning": "#f59e0b",
        "button": "#c2410c",
        "button_text": "#ffffff",
        "input_bg": "#fffaf5",
        "input_text": "#422006",
        "tree_bg": "#ffffff",
        "tree_fg": "#422006",
        "tree_heading": "#fed7aa",
    },
    "onyx": {
        "name": "ONYX",
        "bg": "#0f172a",
        "panel": "#111827",
        "panel_alt": "#1f2937",
        "text": "#f8fafc",
        "muted": "#cbd5e1",
        "primary": "#22c55e",
        "primary_text": "#052e16",
        "danger": "#fb7185",
        "warning": "#fbbf24",
        "button": "#334155",
        "button_text": "#ffffff",
        "input_bg": "#020617",
        "input_text": "#f8fafc",
        "tree_bg": "#0f172a",
        "tree_fg": "#f8fafc",
        "tree_heading": "#334155",
    },
    "minty": {
        "name": "MINTY",
        "bg": "#ecfdf5",
        "panel": "#ffffff",
        "panel_alt": "#d1fae5",
        "text": "#0f172a",
        "muted": "#065f46",
        "primary": "#10b981",
        "primary_text": "#ffffff",
        "danger": "#dc2626",
        "warning": "#ca8a04",
        "button": "#047857",
        "button_text": "#ffffff",
        "input_bg": "#f8fffc",
        "input_text": "#0f172a",
        "tree_bg": "#ffffff",
        "tree_fg": "#0f172a",
        "tree_heading": "#a7f3d0",
    },
    "pearl": {
        "name": "PERLA",
        "bg": "#f8fafc",
        "panel": "#ffffff",
        "panel_alt": "#e2e8f0",
        "text": "#111827",
        "muted": "#475569",
        "primary": "#0ea5e9",
        "primary_text": "#ffffff",
        "danger": "#dc2626",
        "warning": "#d97706",
        "button": "#334155",
        "button_text": "#ffffff",
        "input_bg": "#ffffff",
        "input_text": "#111827",
        "tree_bg": "#ffffff",
        "tree_fg": "#111827",
        "tree_heading": "#bae6fd",
    },
    "velvet": {
        "name": "TERCIOPELO",
        "bg": "#1f1025",
        "panel": "#2a1633",
        "panel_alt": "#3b2147",
        "text": "#f5e9ff",
        "muted": "#d8b4fe",
        "primary": "#c084fc",
        "primary_text": "#1f1025",
        "danger": "#fb7185",
        "warning": "#fbbf24",
        "button": "#7c3aed",
        "button_text": "#ffffff",
        "input_bg": "#14081a",
        "input_text": "#f5e9ff",
        "tree_bg": "#1f1025",
        "tree_fg": "#f5e9ff",
        "tree_heading": "#4c1d95",
    },
    "glacier": {
        "name": "GLACIAR",
        "bg": "#eff8ff",
        "panel": "#ffffff",
        "panel_alt": "#dbeafe",
        "text": "#0f172a",
        "muted": "#334155",
        "primary": "#0284c7",
        "primary_text": "#ffffff",
        "danger": "#dc2626",
        "warning": "#ca8a04",
        "button": "#0369a1",
        "button_text": "#ffffff",
        "input_bg": "#ffffff",
        "input_text": "#0f172a",
        "tree_bg": "#ffffff",
        "tree_fg": "#0f172a",
        "tree_heading": "#bae6fd",
    },
    "ember": {
        "name": "BRASA",
        "bg": "#fff7ed",
        "panel": "#ffffff",
        "panel_alt": "#ffedd5",
        "text": "#431407",
        "muted": "#9a3412",
        "primary": "#ea580c",
        "primary_text": "#ffffff",
        "danger": "#b91c1c",
        "warning": "#f59e0b",
        "button": "#c2410c",
        "button_text": "#ffffff",
        "input_bg": "#fffaf3",
        "input_text": "#431407",
        "tree_bg": "#ffffff",
        "tree_fg": "#431407",
        "tree_heading": "#fed7aa",
    },
    "cosmos": {
        "name": "COSMOS",
        "bg": "#070b18",
        "panel": "#111827",
        "panel_alt": "#1f2a44",
        "text": "#f8fafc",
        "muted": "#93c5fd",
        "primary": "#3b82f6",
        "primary_text": "#ffffff",
        "danger": "#fb7185",
        "warning": "#fbbf24",
        "button": "#1d4ed8",
        "button_text": "#ffffff",
        "input_bg": "#020617",
        "input_text": "#f8fafc",
        "tree_bg": "#0b1120",
        "tree_fg": "#f8fafc",
        "tree_heading": "#1d4ed8",
    },
    "sapphire": {
        "name": "SAFIRA",
        "bg": "#eff6ff",
        "panel": "#ffffff",
        "panel_alt": "#dbeafe",
        "text": "#0f172a",
        "muted": "#334155",
        "primary": "#2563eb",
        "primary_text": "#ffffff",
        "danger": "#dc2626",
        "warning": "#f59e0b",
        "button": "#1e40af",
        "button_text": "#ffffff",
        "input_bg": "#ffffff",
        "input_text": "#0f172a",
        "tree_bg": "#ffffff",
        "tree_fg": "#0f172a",
        "tree_heading": "#bfdbfe",
    },
    "aurora_midnight": {
        "name": "AURORA NOCTURNA",
        "bg": "#08111f",
        "panel": "#111827",
        "panel_alt": "#1f2937",
        "text": "#e2e8f0",
        "muted": "#a7f3d0",
        "primary": "#14b8a6",
        "primary_text": "#052e2b",
        "danger": "#fb7185",
        "warning": "#facc15",
        "button": "#0f766e",
        "button_text": "#ffffff",
        "input_bg": "#020617",
        "input_text": "#e2e8f0",
        "tree_bg": "#0f172a",
        "tree_fg": "#e2e8f0",
        "tree_heading": "#0f766e",
    },
    "plum": {
        "name": "PLUM",
        "bg": "#faf5ff",
        "panel": "#ffffff",
        "panel_alt": "#f3e8ff",
        "text": "#2e1065",
        "muted": "#7e22ce",
        "primary": "#8b5cf6",
        "primary_text": "#ffffff",
        "danger": "#be123c",
        "warning": "#f59e0b",
        "button": "#6d28d9",
        "button_text": "#ffffff",
        "input_bg": "#ffffff",
        "input_text": "#2e1065",
        "tree_bg": "#ffffff",
        "tree_fg": "#2e1065",
        "tree_heading": "#ddd6fe",
    },
    "citrine": {
        "name": "CITRINO",
        "bg": "#fffbeb",
        "panel": "#ffffff",
        "panel_alt": "#fef3c7",
        "text": "#422006",
        "muted": "#a16207",
        "primary": "#eab308",
        "primary_text": "#111111",
        "danger": "#b91c1c",
        "warning": "#d97706",
        "button": "#ca8a04",
        "button_text": "#ffffff",
        "input_bg": "#fffdf3",
        "input_text": "#422006",
        "tree_bg": "#ffffff",
        "tree_fg": "#422006",
        "tree_heading": "#fde68a",
    },
    "titan": {
        "name": "TITAN",
        "bg": "#f8fafc",
        "panel": "#ffffff",
        "panel_alt": "#e2e8f0",
        "text": "#0f172a",
        "muted": "#475569",
        "primary": "#0f766e",
        "primary_text": "#ffffff",
        "danger": "#dc2626",
        "warning": "#d97706",
        "button": "#334155",
        "button_text": "#ffffff",
        "input_bg": "#ffffff",
        "input_text": "#0f172a",
        "tree_bg": "#ffffff",
        "tree_fg": "#0f172a",
        "tree_heading": "#cbd5e1",
    },
    "nebula": {
        "name": "NEBULA",
        "bg": "#0f1020",
        "panel": "#17162f",
        "panel_alt": "#231f45",
        "text": "#f5f3ff",
        "muted": "#c4b5fd",
        "primary": "#7c3aed",
        "primary_text": "#ffffff",
        "danger": "#fb7185",
        "warning": "#fbbf24",
        "button": "#6d28d9",
        "button_text": "#ffffff",
        "input_bg": "#090818",
        "input_text": "#f5f3ff",
        "tree_bg": "#0f1020",
        "tree_fg": "#f5f3ff",
        "tree_heading": "#312e81",
    },
    "arctic": {
        "name": "ARTICO",
        "bg": "#f0f9ff",
        "panel": "#ffffff",
        "panel_alt": "#e0f2fe",
        "text": "#082f49",
        "muted": "#0f4c75",
        "primary": "#0ea5e9",
        "primary_text": "#ffffff",
        "danger": "#dc2626",
        "warning": "#d97706",
        "button": "#0284c7",
        "button_text": "#ffffff",
        "input_bg": "#ffffff",
        "input_text": "#082f49",
        "tree_bg": "#ffffff",
        "tree_fg": "#082f49",
        "tree_heading": "#bae6fd",
    },
    "onyx_gold": {
        "name": "ONIX ORO",
        "bg": "#111111",
        "panel": "#1f1f1f",
        "panel_alt": "#2b2b2b",
        "text": "#f8fafc",
        "muted": "#facc15",
        "primary": "#f59e0b",
        "primary_text": "#111111",
        "danger": "#fb7185",
        "warning": "#fbbf24",
        "button": "#a16207",
        "button_text": "#ffffff",
        "input_bg": "#000000",
        "input_text": "#f8fafc",
        "tree_bg": "#111111",
        "tree_fg": "#f8fafc",
        "tree_heading": "#713f12",
    },
    "prism": {
        "name": "PRISMA",
        "bg": "#f8fafc",
        "panel": "#ffffff",
        "panel_alt": "#eef2ff",
        "text": "#111827",
        "muted": "#6366f1",
        "primary": "#8b5cf6",
        "primary_text": "#ffffff",
        "danger": "#dc2626",
        "warning": "#f59e0b",
        "button": "#4f46e5",
        "button_text": "#ffffff",
        "input_bg": "#ffffff",
        "input_text": "#111827",
        "tree_bg": "#ffffff",
        "tree_fg": "#111827",
        "tree_heading": "#c7d2fe",
    },
    "terra": {
        "name": "TERRACOTA",
        "bg": "#fff7ed",
        "panel": "#ffffff",
        "panel_alt": "#ffedd5",
        "text": "#431407",
        "muted": "#9a3412",
        "primary": "#ea580c",
        "primary_text": "#ffffff",
        "danger": "#b91c1c",
        "warning": "#f59e0b",
        "button": "#c2410c",
        "button_text": "#ffffff",
        "input_bg": "#fffaf5",
        "input_text": "#431407",
        "tree_bg": "#ffffff",
        "tree_fg": "#431407",
        "tree_heading": "#fed7aa",
    },
    "obsidian": {
        "name": "OBSIDIANA",
        "bg": "#09090b",
        "panel": "#111827",
        "panel_alt": "#1f2937",
        "text": "#f8fafc",
        "muted": "#cbd5e1",
        "primary": "#f59e0b",
        "primary_text": "#111111",
        "danger": "#ef4444",
        "warning": "#facc15",
        "button": "#27272a",
        "button_text": "#ffffff",
        "input_bg": "#020617",
        "input_text": "#f8fafc",
        "tree_bg": "#0f172a",
        "tree_fg": "#f8fafc",
        "tree_heading": "#3f3f46",
    },
    "pearl": {
        "name": "PERLA",
        "bg": "#fbfbfd",
        "panel": "#ffffff",
        "panel_alt": "#eef2f7",
        "text": "#111827",
        "muted": "#4b5563",
        "primary": "#0f766e",
        "primary_text": "#ffffff",
        "danger": "#b91c1c",
        "warning": "#b45309",
        "button": "#1d4ed8",
        "button_text": "#ffffff",
        "input_bg": "#ffffff",
        "input_text": "#111827",
        "tree_bg": "#ffffff",
        "tree_fg": "#111827",
        "tree_heading": "#dbeafe",
    },
    "aurora_pro": {
        "name": "AURORA PRO",
        "bg": "#07131f",
        "panel": "#0f1f2f",
        "panel_alt": "#14293d",
        "text": "#f8fafc",
        "muted": "#9ae6b4",
        "primary": "#34d399",
        "primary_text": "#052e16",
        "danger": "#fb7185",
        "warning": "#facc15",
        "button": "#0ea5a4",
        "button_text": "#ffffff",
        "input_bg": "#020617",
        "input_text": "#f8fafc",
        "tree_bg": "#0b1727",
        "tree_fg": "#f8fafc",
        "tree_heading": "#064e3b",
    },
    "ember": {
        "name": "EMBER",
        "bg": "#140f0b",
        "panel": "#22160f",
        "panel_alt": "#2f1d13",
        "text": "#fff7ed",
        "muted": "#fed7aa",
        "primary": "#fb923c",
        "primary_text": "#1f1308",
        "danger": "#ef4444",
        "warning": "#facc15",
        "button": "#c2410c",
        "button_text": "#ffffff",
        "input_bg": "#120c08",
        "input_text": "#fff7ed",
        "tree_bg": "#1c120d",
        "tree_fg": "#fff7ed",
        "tree_heading": "#7c2d12",
    },
    "indigo_pro": {
        "name": "INDIGO PRO",
        "bg": "#0b1020",
        "panel": "#111827",
        "panel_alt": "#1e293b",
        "text": "#f8fafc",
        "muted": "#c7d2fe",
        "primary": "#818cf8",
        "primary_text": "#111827",
        "danger": "#fb7185",
        "warning": "#fbbf24",
        "button": "#4338ca",
        "button_text": "#ffffff",
        "input_bg": "#020617",
        "input_text": "#f8fafc",
        "tree_bg": "#0f172a",
        "tree_fg": "#f8fafc",
        "tree_heading": "#3730a3",
    },
    "champagne": {
        "name": "CHAMPAGNE",
        "bg": "#fffaf1",
        "panel": "#ffffff",
        "panel_alt": "#f5e6c8",
        "text": "#3f2d1f",
        "muted": "#7c5e3c",
        "primary": "#b45309",
        "primary_text": "#ffffff",
        "danger": "#b91c1c",
        "warning": "#d97706",
        "button": "#92400e",
        "button_text": "#ffffff",
        "input_bg": "#fffdf7",
        "input_text": "#3f2d1f",
        "tree_bg": "#ffffff",
        "tree_fg": "#3f2d1f",
        "tree_heading": "#fde68a",
    },
    "jade": {
        "name": "JADE",
        "bg": "#f0fdf4",
        "panel": "#ffffff",
        "panel_alt": "#dcfce7",
        "text": "#10231c",
        "muted": "#315447",
        "primary": "#14b8a6",
        "primary_text": "#ffffff",
        "danger": "#dc2626",
        "warning": "#ca8a04",
        "button": "#0f766e",
        "button_text": "#ffffff",
        "input_bg": "#ffffff",
        "input_text": "#10231c",
        "tree_bg": "#ffffff",
        "tree_fg": "#10231c",
        "tree_heading": "#a7f3d0",
    },
    "twilight": {
        "name": "TWILIGHT",
        "bg": "#111827",
        "panel": "#1f2937",
        "panel_alt": "#334155",
        "text": "#f8fafc",
        "muted": "#cbd5e1",
        "primary": "#38bdf8",
        "primary_text": "#082f49",
        "danger": "#fb7185",
        "warning": "#fbbf24",
        "button": "#475569",
        "button_text": "#ffffff",
        "input_bg": "#0f172a",
        "input_text": "#f8fafc",
        "tree_bg": "#111827",
        "tree_fg": "#f8fafc",
        "tree_heading": "#1e293b",
    },
    "copper": {
        "name": "COBRE",
        "bg": "#fff7ed",
        "panel": "#ffffff",
        "panel_alt": "#ffedd5",
        "text": "#431407",
        "muted": "#7c2d12",
        "primary": "#ea580c",
        "primary_text": "#ffffff",
        "danger": "#b91c1c",
        "warning": "#d97706",
        "button": "#c2410c",
        "button_text": "#ffffff",
        "input_bg": "#fffaf5",
        "input_text": "#431407",
        "tree_bg": "#ffffff",
        "tree_fg": "#431407",
        "tree_heading": "#fed7aa",
    },
    "prism_pro": {
        "name": "PRISMA PRO",
        "bg": "#09111f",
        "panel": "#0f172a",
        "panel_alt": "#1e293b",
        "text": "#f8fafc",
        "muted": "#cbd5e1",
        "primary": "#22d3ee",
        "primary_text": "#082f49",
        "danger": "#fb7185",
        "warning": "#facc15",
        "button": "#7c3aed",
        "button_text": "#ffffff",
        "input_bg": "#020617",
        "input_text": "#f8fafc",
        "tree_bg": "#0f172a",
        "tree_fg": "#f8fafc",
        "tree_heading": "#1d4ed8",
    },
    "onyx": {
        "name": "ONYX",
        "bg": "#09090b",
        "panel": "#18181b",
        "panel_alt": "#27272a",
        "text": "#fafafa",
        "muted": "#d4d4d8",
        "primary": "#60a5fa",
        "primary_text": "#082f49",
        "danger": "#ef4444",
        "warning": "#facc15",
        "button": "#2563eb",
        "button_text": "#ffffff",
        "input_bg": "#111827",
        "input_text": "#fafafa",
        "tree_bg": "#111827",
        "tree_fg": "#fafafa",
        "tree_heading": "#1d4ed8",
    },
    "sapphire": {
        "name": "SAFIRO",
        "bg": "#eff6ff",
        "panel": "#ffffff",
        "panel_alt": "#dbeafe",
        "text": "#0f172a",
        "muted": "#334155",
        "primary": "#2563eb",
        "primary_text": "#ffffff",
        "danger": "#dc2626",
        "warning": "#d97706",
        "button": "#1d4ed8",
        "button_text": "#ffffff",
        "input_bg": "#ffffff",
        "input_text": "#0f172a",
        "tree_bg": "#ffffff",
        "tree_fg": "#0f172a",
        "tree_heading": "#bfdbfe",
    },
    "pine": {
        "name": "PINO",
        "bg": "#f0fdf4",
        "panel": "#ffffff",
        "panel_alt": "#dcfce7",
        "text": "#10231c",
        "muted": "#315447",
        "primary": "#15803d",
        "primary_text": "#ffffff",
        "danger": "#b91c1c",
        "warning": "#a16207",
        "button": "#166534",
        "button_text": "#ffffff",
        "input_bg": "#f9fffb",
        "input_text": "#10231c",
        "tree_bg": "#ffffff",
        "tree_fg": "#10231c",
        "tree_heading": "#bbf7d0",
    },
    "blush": {
        "name": "BLUSH",
        "bg": "#fff1f2",
        "panel": "#ffffff",
        "panel_alt": "#ffe4e6",
        "text": "#3f1d2e",
        "muted": "#7f1d1d",
        "primary": "#e11d48",
        "primary_text": "#ffffff",
        "danger": "#be123c",
        "warning": "#f59e0b",
        "button": "#9f1239",
        "button_text": "#ffffff",
        "input_bg": "#fff7f7",
        "input_text": "#3f1d2e",
        "tree_bg": "#ffffff",
        "tree_fg": "#3f1d2e",
        "tree_heading": "#fecdd3",
    },
    "pebble": {
        "name": "PEBBLE",
        "bg": "#f8fafc",
        "panel": "#ffffff",
        "panel_alt": "#e2e8f0",
        "text": "#0f172a",
        "muted": "#475569",
        "primary": "#64748b",
        "primary_text": "#ffffff",
        "danger": "#b91c1c",
        "warning": "#b45309",
        "button": "#334155",
        "button_text": "#ffffff",
        "input_bg": "#ffffff",
        "input_text": "#0f172a",
        "tree_bg": "#ffffff",
        "tree_fg": "#0f172a",
        "tree_heading": "#cbd5e1",
    },
    "citrus": {
        "name": "CITRUS",
        "bg": "#fffbeb",
        "panel": "#ffffff",
        "panel_alt": "#fef3c7",
        "text": "#422006",
        "muted": "#78350f",
        "primary": "#f59e0b",
        "primary_text": "#111111",
        "danger": "#dc2626",
        "warning": "#d97706",
        "button": "#b45309",
        "button_text": "#ffffff",
        "input_bg": "#fffdf3",
        "input_text": "#422006",
        "tree_bg": "#ffffff",
        "tree_fg": "#422006",
        "tree_heading": "#fde68a",
    },
    "mauve": {
        "name": "MAUVE",
        "bg": "#faf5ff",
        "panel": "#ffffff",
        "panel_alt": "#f3e8ff",
        "text": "#2e1065",
        "muted": "#6b21a8",
        "primary": "#7c3aed",
        "primary_text": "#ffffff",
        "danger": "#be123c",
        "warning": "#d97706",
        "button": "#6d28d9",
        "button_text": "#ffffff",
        "input_bg": "#fffaff",
        "input_text": "#2e1065",
        "tree_bg": "#ffffff",
        "tree_fg": "#2e1065",
        "tree_heading": "#e9d5ff",
    },
    "teal_mist": {
        "name": "TEAL MIST",
        "bg": "#f0fdfa",
        "panel": "#ffffff",
        "panel_alt": "#ccfbf1",
        "text": "#042f2e",
        "muted": "#115e59",
        "primary": "#14b8a6",
        "primary_text": "#ffffff",
        "danger": "#ef4444",
        "warning": "#f59e0b",
        "button": "#0f766e",
        "button_text": "#ffffff",
        "input_bg": "#f8fffe",
        "input_text": "#042f2e",
        "tree_bg": "#ffffff",
        "tree_fg": "#042f2e",
        "tree_heading": "#99f6e4",
    },
    "wine": {
        "name": "WINE",
        "bg": "#fff1f2",
        "panel": "#ffffff",
        "panel_alt": "#ffe4e6",
        "text": "#4c0519",
        "muted": "#7f1d1d",
        "primary": "#be123c",
        "primary_text": "#ffffff",
        "danger": "#991b1b",
        "warning": "#f59e0b",
        "button": "#9f1239",
        "button_text": "#ffffff",
        "input_bg": "#fffafb",
        "input_text": "#4c0519",
        "tree_bg": "#ffffff",
        "tree_fg": "#4c0519",
        "tree_heading": "#fecdd3",
    },
    "polar": {
        "name": "POLAR",
        "bg": "#eff6ff",
        "panel": "#ffffff",
        "panel_alt": "#dbeafe",
        "text": "#0f172a",
        "muted": "#334155",
        "primary": "#38bdf8",
        "primary_text": "#082f49",
        "danger": "#dc2626",
        "warning": "#ca8a04",
        "button": "#0369a1",
        "button_text": "#ffffff",
        "input_bg": "#ffffff",
        "input_text": "#0f172a",
        "tree_bg": "#ffffff",
        "tree_fg": "#0f172a",
        "tree_heading": "#bae6fd",
    },
    "midnight_blue": {
        "name": "MIDNIGHT BLUE",
        "bg": "#020617",
        "panel": "#0f172a",
        "panel_alt": "#1e293b",
        "text": "#e2e8f0",
        "muted": "#94a3b8",
        "primary": "#60a5fa",
        "primary_text": "#ffffff",
        "danger": "#f87171",
        "warning": "#fbbf24",
        "button": "#1d4ed8",
        "button_text": "#ffffff",
        "input_bg": "#111827",
        "input_text": "#f8fafc",
        "tree_bg": "#0f172a",
        "tree_fg": "#e2e8f0",
        "tree_heading": "#1e3a8a",
    },
    "copper": {
        "name": "COPPER",
        "bg": "#1c1410",
        "panel": "#2a1f18",
        "panel_alt": "#3d2c22",
        "text": "#fde8d8",
        "muted": "#c4a484",
        "primary": "#ea580c",
        "primary_text": "#ffffff",
        "danger": "#dc2626",
        "warning": "#f59e0b",
        "button": "#9a3412",
        "button_text": "#ffffff",
        "input_bg": "#241a14",
        "input_text": "#fde8d8",
        "tree_bg": "#2a1f18",
        "tree_fg": "#fde8d8",
        "tree_heading": "#7c2d12",
    },
    "forest_deep": {
        "name": "FOREST DEEP",
        "bg": "#052e16",
        "panel": "#14532d",
        "panel_alt": "#166534",
        "text": "#ecfdf5",
        "muted": "#86efac",
        "primary": "#4ade80",
        "primary_text": "#052e16",
        "danger": "#f87171",
        "warning": "#facc15",
        "button": "#15803d",
        "button_text": "#ffffff",
        "input_bg": "#064e3b",
        "input_text": "#ecfdf5",
        "tree_bg": "#14532d",
        "tree_fg": "#ecfdf5",
        "tree_heading": "#166534",
    },
    "sakura": {
        "name": "SAKURA",
        "bg": "#fff1f5",
        "panel": "#ffffff",
        "panel_alt": "#fce7f3",
        "text": "#831843",
        "muted": "#9d174d",
        "primary": "#ec4899",
        "primary_text": "#ffffff",
        "danger": "#e11d48",
        "warning": "#d97706",
        "button": "#be185d",
        "button_text": "#ffffff",
        "input_bg": "#fff7fb",
        "input_text": "#831843",
        "tree_bg": "#ffffff",
        "tree_fg": "#831843",
        "tree_heading": "#fbcfe8",
    },
    "graphite": {
        "name": "GRAPHITE",
        "bg": "#18181b",
        "panel": "#27272a",
        "panel_alt": "#3f3f46",
        "text": "#fafafa",
        "muted": "#a1a1aa",
        "primary": "#a1a1aa",
        "primary_text": "#18181b",
        "danger": "#ef4444",
        "warning": "#eab308",
        "button": "#52525b",
        "button_text": "#ffffff",
        "input_bg": "#27272a",
        "input_text": "#fafafa",
        "tree_bg": "#27272a",
        "tree_fg": "#fafafa",
        "tree_heading": "#3f3f46",
    },
    "neon_lime": {
        "name": "NEON LIME",
        "bg": "#0a0f00",
        "panel": "#141f05",
        "panel_alt": "#1f2e0a",
        "text": "#ecfccb",
        "muted": "#bef264",
        "primary": "#a3e635",
        "primary_text": "#1a2e05",
        "danger": "#fb7185",
        "warning": "#fde047",
        "button": "#4d7c0f",
        "button_text": "#ffffff",
        "input_bg": "#141f05",
        "input_text": "#ecfccb",
        "tree_bg": "#141f05",
        "tree_fg": "#ecfccb",
        "tree_heading": "#365314",
    },
    "coral_reef": {
        "name": "CORAL REEF",
        "bg": "#ecfeff",
        "panel": "#ffffff",
        "panel_alt": "#cffafe",
        "text": "#164e63",
        "muted": "#0e7490",
        "primary": "#f97316",
        "primary_text": "#ffffff",
        "danger": "#dc2626",
        "warning": "#eab308",
        "button": "#0891b2",
        "button_text": "#ffffff",
        "input_bg": "#f0fdff",
        "input_text": "#164e63",
        "tree_bg": "#ffffff",
        "tree_fg": "#164e63",
        "tree_heading": "#a5f3fc",
    },
    "arctic": {
        "name": "ARCTIC",
        "bg": "#f8fafc",
        "panel": "#ffffff",
        "panel_alt": "#e2e8f0",
        "text": "#0f172a",
        "muted": "#64748b",
        "primary": "#0ea5e9",
        "primary_text": "#ffffff",
        "danger": "#e11d48",
        "warning": "#f59e0b",
        "button": "#475569",
        "button_text": "#ffffff",
        "input_bg": "#ffffff",
        "input_text": "#0f172a",
        "tree_bg": "#ffffff",
        "tree_fg": "#0f172a",
        "tree_heading": "#cbd5e1",
    },
    "espresso": {
        "name": "ESPRESSO",
        "bg": "#1c1917",
        "panel": "#292524",
        "panel_alt": "#44403c",
        "text": "#fafaf9",
        "muted": "#a8a29e",
        "primary": "#d6d3d1",
        "primary_text": "#1c1917",
        "danger": "#ef4444",
        "warning": "#f59e0b",
        "button": "#78350f",
        "button_text": "#ffffff",
        "input_bg": "#292524",
        "input_text": "#fafaf9",
        "tree_bg": "#292524",
        "tree_fg": "#fafaf9",
        "tree_heading": "#57534e",
    },
    "royal_gold": {
        "name": "ROYAL GOLD",
        "bg": "#1a1625",
        "panel": "#2e2640",
        "panel_alt": "#3f3558",
        "text": "#faf5ff",
        "muted": "#c4b5fd",
        "primary": "#fbbf24",
        "primary_text": "#1a1625",
        "danger": "#f43f5e",
        "warning": "#fb923c",
        "button": "#6d28d9",
        "button_text": "#ffffff",
        "input_bg": "#2e2640",
        "input_text": "#faf5ff",
        "tree_bg": "#2e2640",
        "tree_fg": "#faf5ff",
        "tree_heading": "#4c1d95",
    },
    "slate_rose": {
        "name": "SLATE ROSE",
        "bg": "#1e293b",
        "panel": "#334155",
        "panel_alt": "#475569",
        "text": "#fce7f3",
        "muted": "#fda4af",
        "primary": "#fb7185",
        "primary_text": "#ffffff",
        "danger": "#ef4444",
        "warning": "#fbbf24",
        "button": "#64748b",
        "button_text": "#ffffff",
        "input_bg": "#334155",
        "input_text": "#fce7f3",
        "tree_bg": "#334155",
        "tree_fg": "#fce7f3",
        "tree_heading": "#475569",
    },
}


@lru_cache(maxsize=16)
def load_app_logo(size: int = 48):
    if Image is None or ImageTk is None:
        return None
    root = Path(__file__).resolve().parent.parent
    candidates = (
        root / "assets" / "Arezone.ico",
        root / "assets" / "AREZONE.ico",
    )
    for path in candidates:
        if not path.exists():
            continue
        try:
            image = Image.open(path).convert("RGBA")
            image.thumbnail((size, size), Image.LANCZOS)
            return ImageTk.PhotoImage(image)
        except Exception:
            continue
    return None


def apply_window_icon(window: tk.Misc) -> bool:
    root = Path(__file__).resolve().parent.parent
    candidates = (
        root / "assets" / "Arezone.ico",
        root / "assets" / "AREZONE.ico",
    )
    for path in candidates:
        if not path.exists():
            continue
        try:
            window.iconbitmap(str(path))
            return True
        except tk.TclError:
            continue
    logo = load_app_logo(32)
    if logo is not None:
        try:
            window.iconphoto(True, logo)
            setattr(window, "_arezone_icon_ref", logo)
            return True
        except tk.TclError:
            return False
    return False

THEME_CHOICES = tuple(THEMES.keys())


FONT_TITLE = ("Segoe UI", 30, "bold")
FONT_BIG = ("Segoe UI", 20, "bold")
FONT_NORMAL = ("Segoe UI", 18, "bold")
FONT_TEXT = ("Segoe UI", 16)
FONT_TABLE = ("Segoe UI", 16)


class ThemeMixin:
    theme_name: str

    @property
    def colors(self) -> dict[str, str]:
        return THEMES.get(getattr(self, "theme_name", "day"), THEMES["day"])

    def apply_common_styles(self) -> None:
        c = self.colors
        style = ttk.Style()
        style.theme_use("clam")
        style.configure("Senior.TFrame", background=c["bg"])
        style.configure("Panel.TFrame", background=c["panel"])
        style.configure("Senior.TLabel", background=c["bg"], foreground=c["text"], font=FONT_TEXT)
        style.configure("Panel.TLabel", background=c["panel"], foreground=c["text"], font=FONT_TEXT)
        style.configure("Title.TLabel", background=c["bg"], foreground=c["text"], font=FONT_TITLE)
        style.configure("Big.TLabel", background=c["panel"], foreground=c["text"], font=FONT_BIG)
        style.configure("Senior.TEntry", fieldbackground=c["input_bg"], foreground=c["input_text"], font=FONT_BIG)
        style.configure("Treeview", background=c["tree_bg"], foreground=c["tree_fg"], fieldbackground=c["tree_bg"], rowheight=48, font=FONT_TABLE)
        style.configure("Treeview.Heading", background=c["tree_heading"], foreground=c["text"], font=("Segoe UI", 15, "bold"))
        style.map("Treeview", background=[("selected", c["primary"])], foreground=[("selected", c["primary_text"])])
        try:
            apply_window_icon(self.winfo_toplevel())
        except Exception:
            pass


def set_tree_theme(tree: ttk.Treeview, theme_name: str) -> None:
    c = THEMES.get(theme_name, THEMES["day"])
    tree.tag_configure("odd", background=c["tree_bg"], foreground=c["tree_fg"])
    tree.tag_configure("even", background=c["panel_alt"], foreground=c["text"])


def big_button(
    parent,
    text: str,
    command,
    theme_name: str,
    *,
    bg: str | None = None,
    fg: str | None = None,
    height: int = 2,
) -> tk.Button:
    c = THEMES.get(theme_name, THEMES["day"])
    normal_bg = bg or c["button"]
    normal_fg = fg or c["button_text"]
    active_bg = c["primary"]
    active_fg = c["primary_text"]
    normal_font = FONT_BIG
    focus_font = ("Segoe UI", 21, "bold")

    def _on_click():
        command()

    def _on_enter(_event=None):
        try:
            widget.configure(bg=active_bg, fg=active_fg, relief="raised")
        except tk.TclError:
            pass

    def _on_leave(_event=None):
        if widget == widget.focus_get():
            return
        try:
            widget.configure(bg=normal_bg, fg=normal_fg, relief="raised")
        except tk.TclError:
            pass

    def _on_focus(_event=None):
        try:
            widget.configure(
                bg=active_bg,
                fg=active_fg,
                bd=6,
                font=focus_font,
                highlightbackground=c["primary"],
                highlightcolor=c["primary"],
                highlightthickness=4,
            )
        except tk.TclError:
            pass

    def _on_blur(_event=None):
        try:
            widget.configure(
                bg=normal_bg,
                fg=normal_fg,
                bd=4,
                font=normal_font,
                highlightbackground=normal_bg,
                highlightcolor=normal_bg,
                highlightthickness=2,
            )
        except tk.TclError:
            pass

    widget = tk.Button(
        parent,
        text=text,
        command=_on_click,
        bg=normal_bg,
        fg=normal_fg,
        activebackground=active_bg,
        activeforeground=active_fg,
        relief="raised",
        bd=4,
        height=height,
        font=normal_font,
        cursor="hand2",
        wraplength=300,
        takefocus=True,
        highlightbackground=normal_bg,
        highlightcolor=normal_bg,
        highlightthickness=2,
    )
    widget.bind("<Enter>", _on_enter)
    widget.bind("<Leave>", _on_leave)
    widget.bind("<FocusIn>", _on_focus)
    widget.bind("<FocusOut>", _on_blur)
    return widget


def app_logo_label(parent, theme_name: str, *, size: int = 48, panel: bool = False) -> tk.Label:
    c = THEMES.get(theme_name, THEMES["day"])
    image = load_app_logo(size)
    label = tk.Label(
        parent,
        bg=c["panel"] if panel else c["bg"],
        fg=c["text"],
        font=("Segoe UI", max(12, size // 2), "bold"),
        anchor="center",
    )
    if image is not None:
        label.configure(image=image, text="")
        label.image = image  # keep a live reference
    else:
        label.configure(text="A")
    return label


def plain_label(parent, text: str, theme_name: str, *, big: bool = False, panel: bool = False) -> tk.Label:
    c = THEMES.get(theme_name, THEMES["day"])
    return tk.Label(
        parent,
        text=text,
        bg=c["panel"] if panel else c["bg"],
        fg=c["text"],
        font=FONT_BIG if big else FONT_TEXT,
        anchor="w",
    )


def themed_frame(parent, theme_name: str, *, panel: bool = False, border: bool = False) -> tk.Frame:
    c = THEMES.get(theme_name, THEMES["day"])
    return tk.Frame(
        parent,
        bg=c["panel"] if panel else c["bg"],
        bd=2 if border else 0,
        relief="solid" if border else "flat",
        highlightbackground=c["primary"],
        highlightthickness=2 if border else 0,
    )


def ps5_glow_button(
    parent,
    text: str,
    command,
    theme_name: str,
    *,
    bg: str | None = None,
    fg: str | None = None,
    danger: bool = False,
    compact: bool = False,
    large: bool = False,
    glow_color: str | None = None,
    glow_fg: str | None = None,
) -> tk.Button:
    c = THEMES.get(theme_name, THEMES["night"])
    glow = glow_color or c["primary"]
    glow_text = glow_fg if glow_fg is not None else c["primary_text"]
    normal_bg = bg or (c["danger"] if danger else c["button"])
    normal_fg = fg if fg is not None else c["button_text"]
    if large:
        base_font = ("Segoe UI", 17, "bold")
        glow_font = ("Segoe UI", 20, "bold")
    elif compact:
        base_font = ("Segoe UI", 12, "bold")
        glow_font = ("Segoe UI", 13, "bold")
    else:
        base_font = ("Segoe UI", 14, "bold")
        glow_font = ("Segoe UI", 16, "bold")
    widget = tk.Button(
        parent,
        text=text,
        command=command,
        bg=normal_bg,
        fg=normal_fg,
        activebackground=glow,
        activeforeground=glow_text,
        font=base_font,
        relief="flat",
        bd=0,
        padx=8 if compact else (18 if large else 12),
        pady=4 if compact else (12 if large else 8),
        cursor="hand2",
        takefocus=True,
        highlightthickness=2,
        highlightbackground=normal_bg,
        highlightcolor=normal_bg,
    )
    widget._ps5_normal = (normal_bg, normal_fg, base_font, 2)  # type: ignore[attr-defined]
    widget._ps5_anim = None  # type: ignore[attr-defined]

    def _apply_glow(on: bool) -> None:
        if widget._ps5_anim:  # type: ignore[attr-defined]
            widget.after_cancel(widget._ps5_anim)
            widget._ps5_anim = None
        if on:
            widget.configure(
                bg=glow,
                fg=glow_text,
                font=glow_font,
                highlightbackground=glow,
                highlightcolor=glow,
                highlightthickness=5,
            )
        else:
            nb, nf, bf, ht = widget._ps5_normal  # type: ignore[attr-defined]
            widget.configure(bg=nb, fg=nf, font=bf, highlightbackground=nb, highlightcolor=nb, highlightthickness=ht)

    def _pulse(step: int = 0, growing: bool = True) -> None:
        if not widget.winfo_exists():
            return
        if large:
            sizes = (15, 17, 19, 20)
        elif compact:
            sizes = (11, 12, 13, 14)
        else:
            sizes = (12, 13, 14, 15)
        if growing:
            idx = min(step, len(sizes) - 1)
            widget.configure(font=("Segoe UI", sizes[idx], "bold"))
            if step < len(sizes) - 1:
                widget._ps5_anim = widget.after(18, lambda: _pulse(step + 1, True))  # type: ignore[attr-defined]
        else:
            idx = max(0, len(sizes) - 1 - step)
            widget.configure(font=("Segoe UI", sizes[idx], "bold"))
            if step < len(sizes) - 1:
                widget._ps5_anim = widget.after(18, lambda: _pulse(step + 1, False))  # type: ignore[attr-defined]
            else:
                _apply_glow(False)

    def _on_enter(_e=None):
        _apply_glow(True)
        _pulse(0, True)

    def _on_leave(_e=None):
        if widget.focus_get() is widget:
            return
        _pulse(0, False)

    def _on_focus_in(_e=None):
        _on_enter()

    def _on_focus_out(_e=None):
        _on_leave()

    widget.bind("<Enter>", _on_enter)
    widget.bind("<Leave>", _on_leave)
    widget.bind("<FocusIn>", _on_focus_in)
    widget.bind("<FocusOut>", _on_focus_out)
    return widget


def fit_window(window, width: int, height: int, *, min_width: int | None = None, min_height: int | None = None) -> None:
    window.update_idletasks()
    screen_width = max(window.winfo_screenwidth(), 1024)
    screen_height = max(window.winfo_screenheight(), 720)
    target_width = min(width, max(820, int(screen_width * 0.94)))
    target_height = min(height, max(580, int(screen_height * 0.92)))
    min_w = min_width or min(target_width, 820)
    min_h = min_height or min(target_height, 580)
    window.minsize(min_w, min_h)
    x = max(0, (screen_width - target_width) // 2)
    y = max(0, (screen_height - target_height) // 2)
    window.geometry(f"{target_width}x{target_height}+{x}+{y}")
